//auth action
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

//registration action
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

//orders action
export const FETCH_ORDER_LIST_REQUEST = 'FETCH_ORDER_LIST_REQUEST';
export const FETCH_ORDER_LIST_SUCCESS = 'FETCH_ORDER_LIST_SUCCESS';
export const FETCH_ORDER_LIST_FAILURE = 'FETCH_ORDER_LIST_FAILURE';
export const REFRESH_ORDER_LIST_REQUEST = 'REFRESH_ORDER_LIST_REQUEST';
export const REFRESH_ORDER_LIST_SUCCESS = 'REFRESH_ORDER_LIST_SUCCESS';
export const REFRESH_ORDER_LIST_FAILURE = 'REFRESH_ORDER_LIST_FAILURE';

//order action
export const FETCH_ORDER_DETAIL_REQUEST = 'FETCH_ORDER_DETAIL_REQUEST';
export const FETCH_ORDER_DETAIL_SUCCESS = 'FETCH_ORDER_DETAIL_SUCCESS';
export const FETCH_ORDER_DETAIL_FAILURE = 'FETCH_ORDER_DETAIL_FAILURE';

//saga action
export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';

export const FETCH_ORDER_LIST = 'FETCH_ORDER_LIST';
export const REFRESH_ORDER_LIST = 'REFRESH_ORDER_LIST';

export const FETCH_ORDER_DETAIL = 'FETCH_ORDER_DETAIL';
